### ISSUE TITLE
Forward plot.console arg from install.snowball() to installation.feedback()

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#10]
`install.snowball()` has a `plot.console` boolean argument, that the user can switch:

https://github.com/Bisaloo/groundhogR/blob/053fba98e83558260cc095cefdd5a0d3c39de108/R/install.snowball.R#L11-L13

should this argument be forwarded to installation.feedback() (which is currently always set to `TRUE`):

https://github.com/Bisaloo/groundhogR/blob/053fba98e83558260cc095cefdd5a0d3c39de108/R/install.snowball.R#L52

**Comment by urisohn** [comment]
yes it should. good catch.

**Comment by Bisaloo** [comment]
Thanks for your answer, it's a bit simpler for me if you don't close the issues. I'll do it when the fix is actually live :).

**Comment by urisohn** [comment]
ok

------ Original Message ------
