### ISSUE TITLE
Return TRUE/FALSE or get.active()$pkg_vrs in groundhog.library()

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#18]
`groundhog.library()` currently returns `NULL` it would make more sense to return `TRUE`/`FALSE` or `get.active()$pkg_vrs` to match `library()`'s behaviour:

> Normally library returns (invisibly) the list of attached packages, but TRUE or FALSE if logical.return is TRUE.

**Comment by urisohn** [comment]
so TRUE is returned if the package is succesully loaded?
Would it make sense to instead return more information? Say what dependencies were included or if the package was already installed? 
What's the purpose of this return you think?

**Comment by Bisaloo** [comment]
R functions will always return a result. So it's better to be mindful of what we return instead letting R default to the last evaluation, which may be completely meaningless.

Currently, `groundhog.library()` returns `NULL`, which is not too bad since it's not anything misleading at least. But we could return something use this return to provide more information to the user.

> so TRUE is returned if the package is succesully loaded?

Yes, that would be useful if users want to automatically detect if everything went smoothly or not. Currently, they have to rely on the final message:

https://github.com/Bisaloo/groundhogR/blob/9fd65a3c5d4e26c0fe49569bdf7646484de888b4/R/groundhog.library.R#L53-L58

which introduces extra steps if they want to test if `groundhog.library()` succeeded (catch the message and test its content).

> Would it make sense to instead return more information? Say what dependencies were included or if the package was already installed?

That's another option. To somewhat mimic the default behaviour of `library()`, we could return `get.active()$pkg_vrs`.

My initial intuition was to return `TRUE`/`FALSE` but I don't have very strong feelings on this vs `get.active()$pkg_vrs`.

**Comment by urisohn** [comment]
ok, will think a few minutes about this

Fixed the space issue, sorry. Had written the extra function to kill 
spaces but was not being run.

Should be resolved now.

Uri


------ Original Message ------

**Comment by urisohn** [comment]
If it were easy to implement seems like a list() would make sense

success: TRUE/FALSE providing the inforamtion that the message at then end is providing.
active: get.active()$pkg_vrs
loaded: set of package versions  that were already installed and were merely loaded
installed: set of package versions that needed to be installed

I can imagine this being useful if users have bugs that they want to convey to us.

BUt i am not sure, if you have a reason against this, let's go with get.active()$pkg_vrs

**Comment by Bisaloo** [comment]
Yes, it's pretty easy to implement.

But I would vote against this if it's just a matter of getting debugging info from users. The list seems really hard to understand and manipulate for users compared to a simple `TRUE`/`FALSE` or a data.frame in the case of  `get.active()$pkg_vrs`. Debugging info can easily be obtained via other means on the case by case basis.

So I think I'll go with `get.active()$pkg_vrs`. Please let me know if you disagree.

**Comment by urisohn** [comment]
that's fine, thank you,
