### ISSUE TITLE
Published column is broken for some packages server side

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#21]
Reprex:

```r
tmp <- tempfile()

download.file("http://groundhogr.com/cran.toc.rds", tmp)

cran.toc <- readRDS(tmp)

cran.toc[cran.toc$Package == "COVID19",]
#>        Package Version                                                                 Imports Depends Suggests
#> 488    COVID19   0.2.1 devtools,utils,reshape2,dplyr,tidyr,sp,rgdal,ggplot2,gganimate,ggthemes        R         
#> 235610 COVID19   0.3.0                                     devtools,utils,reshape2,dplyr,tidyr                 
#>        Published
#> 488    2020-03-31
#> 235610      18363
```

It may be worthwhile to implement automated tests to the script producing the files on the server as well at some point.

**Comment by urisohn** [comment]
Ok, this arose as a side-effect of fixing the space in dependencies bug.
It is fixed now.

I like the idea of a check on the update of the server, but am not sure what exactly that would look like. I get an email everyday with the added files and give it a look, I would have gotten the email tomorrow and spotted the weird date, I think.

Checking that a date is not a date seems easy, but what other checks would you do?

**Comment by urisohn** [comment]
(all rows with broken dates were from today's update)

**Comment by Bisaloo** [comment]
For starters, the same tests that I run on the local files:

https://github.com/Bisaloo/groundhogR/blob/41a36655338b0b98cbd54f26453e638528d4a653/tests/testthat/test-toc.R#L5-L16

It would make sense to verify that the table grows every day as well.

At some point, I was checking if the file was sorted by date but it didn't work, I don't know if that's expected or not.

I can take care of the tests if we start a new repository with the server scripts. I can also set up email alerts for failed tests once everything works well.

**Comment by urisohn** [comment]
what do you mean by 'start a new repository'?

the update is based on the .rds files they post for cran:
con=url("https://cran.r-project.org/web/packages/packages.rds")  #RDS file with all current packages
      ap=data.frame(readRDS(con))
      close(con)

but for older files, i downloaded the entire set of tar.ballls and looped through processing the DESCRIPTION files, so it's a pain to restard

You can give them a look here:
http://groundhogr.com/[5]_cron-job_update_toc.cran.R
http://groundhogr.com/[6]_cron-job_update_install.times.R

**Comment by Bisaloo** [comment]
I think it would be nice at some point to create a 2nd repository on GitHub with these R files. This way, users/developers could review the script and be convinced that groundhogR actually does what it says: both on the package side and on the server side.

**Comment by urisohn** [comment]
ah, ok. sure, makes sense.
i thought you meant something else (starting the cran.toc files from scratch)

**Comment by Bisaloo** [comment]
Closing this issue since it's been fixed. We can continue the discussion about publishing the server scripts elsewhere (in a new issue or by email).
