### ISSUE TITLE
Auto-detect if users are running R within RStudio to print appropriate message?

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#3]
I think the best way to do this is using:

```r
Sys.getenv("RSTUDIO")=="1"
```

**Comment by urisohn** [comment]
OK.

**Comment by urisohn** [comment]
Actually, this deviates a bit from making the script as simple as possible. 
the goal is perfection for 80% of users. More than 80% use R Studio, and the instructions do tell users to re-start R. If you think there are ambiguities let's clarify the langauge, but let's not add a bunch of code written by someone else. More moving parts, more breaking parts.

So, let's not do this. Let's not worry about non R Studio users at all, just with a message "if you are not using R Studio, restart R to continue"
