### ISSUE TITLE
Optimize toc files server-side

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#8]
- [x] ~~The `pkg_vrs` column could be created server side~~ 
Made obsolete by 79436779787708d5d4e70761a48b8aa88de60776.

https://github.com/Bisaloo/groundhogR/blob/f99dc5f5f7b547fca7d1ff0debe355ae02659ac9/R/load.cran.toc.R#L40-L41

- [x] The first column should be removed since it's discarded as soon as the file is loaded. It needlessly slow things down.

https://github.com/Bisaloo/groundhogR/blob/f99dc5f5f7b547fca7d1ff0debe355ae02659ac9/R/load.cran.toc.R#L36-L37

**Comment by urisohn** [comment]
I don't have the pkg_vrs on the server becuase it ads substantially to its weight, but let's have a conversation about this issue, i am not 100% sure what the best place to store the constantly updated toc file is. Curious if you have ideas. 
the 1st column is generated when saving a .csv file, I am fixing that on the server side to have row.names=F. So from now on the toc files will no longer have the 1st column to drop, the code should be adjusted accordingly

**Comment by urisohn** [comment]
edit completed. so right now the toc files no longer have the 1st column being dropped by groundhogR, that line should be dropped from the code.

**Comment by Bisaloo** [comment]
I think it would also make sense to store `cran.times$update.date` as a `Date` server side. It is currently the case to `cran.toc$Published` but not for  `cran.times$update.date`.

**Comment by Bisaloo** [comment]
@urisohn, what you do think about storing the `update.date` as a `Date` in `cran.times.rds` on the server?

**Comment by urisohn** [comment]
had missed that, sorry. should be fixed now and the .rds file on the server already has the update.date as a Date
